### ISSUE TITLE
Collect activations

### ISSUE THREAD

**Issue by qinliu9** [minicheshire/Robust-Prefix-Tuning#1]
Excuse me but where did you implement the step of "collect activations by correctly classified data" ?
Accordingly, where is the distance (step 3 in Figure 1) calculated?
Thanks!

**Comment by minicheshire** [comment]
Hi @QLiu-NLP, 

Thanks for your interest in our work! Steps 1 and 2 are both implemented in get_proj.py. For step 1, you can refer to Line 113 in get_proj.py (https://github.com/minicheshire/Robust-Prefix-Tuning/blob/main/get_proj.py#L113): the activations are gathered in ``save_hidden_states". The projection is obtained with PCA in Lines 117~122 (also in get_proj.py, https://github.com/minicheshire/Robust-Prefix-Tuning/blob/main/get_proj.py#L117-L122). 

As for Step 3, the distance is calculated on the fly during the inference phase (which serves as the loss for the optimization of the additional prefix Ѱ) and is implemented in both test_robust_prefix_psi_insent.py and test_robust_prefix_psi_uat.py. Take test_robust_prefix_psi_insent.py as an example: Lines 85-89 (https://github.com/minicheshire/Robust-Prefix-Tuning/blob/main/test_robust_prefix_psi_insent.py#L85-L89) calculates the distance (saved in "loss_layer"), which is later optimized to update Ѱ (the "s_tokens_control" in the code).

Let me know if these answered your questions :)

**Comment by qinliu9** [comment]
Thanks for your prompt reply. It helps a lot :D
