### ISSUE TITLE
Question about generating adversarial examples

### ISSUE THREAD

**Issue by ruizheng20** [minicheshire/Robust-Prefix-Tuning#4]
Hi,

In your experimental setting, are the adversarial examples generated in advance (statically) and then optimize robust prefix embeddings accordingly to defend against them?

Looking forward to your reply,
Thanks.

**Comment by minicheshire** [comment]
Yes. We assume the attacks are targeted at the original prefix embeddings, so we generate adversarial examples before the test-time optimization of the additional robust prefix. 

Hope this helps. Thanks for your interest in our work!
