### ISSUE TITLE
Question about adv. prefix-tuning

### ISSUE THREAD

**Issue by Ericmututu** [minicheshire/Robust-Prefix-Tuning#5]
Hi,

Thanks for sharing this wonderful work! I have a question about the `adv. prefix-tuning` in Table 6. In the appendix, it is mentioned that the adversarial training baseline is from Miyato et al. 2017. However, for the [line](https://github.com/minicheshire/Robust-Prefix-Tuning/blob/c4eca6a8311f3510c290faccfba6ca3d06e5dc59/train_adv.py#L151) in `train_adv.py`,  the adversarial training is PGD. I would like to know which method is applied in the paper?

I am new to this field,  which may lead to asking naive questions.

Thank you in advance!

**Comment by minicheshire** [comment]
Hi,

Thanks for your interest in our work! According to my understanding, Miyato et al. (2017) (Adversarial Training Methods for Semi Supervised Text Classification, https://openreview.net/pdf?id=r1X3g2_xl) is equivalent to applying PGD training to text classification (check the Eq. (2) in the paper), so I used it in implementation. 

Hope this helps!

**Comment by Ericmututu** [comment]
Thank you for your reply, I understand.
